openapi: 3.0.0
info:
  title: Subscription Service API
  version: 1.0.0
  description: API сервиса управления подписками, позволяющий создавать, обновлять, удалять и просматривать подписки пользователей на различные сервисы

tags:
  - name: Health
    description: Проверка работоспособности сервиса
  - name: Subscriptions
    description: Операции с подписками

paths:
  /:
    get:
      tags:
        - Health
      summary: Check service status
      description: Проверка работоспособности сервиса
      responses:
        '200':
          description: Сервис работает нормально
        '500':
          description: Сервис недоступен

  /subscriptions:
    post:
      summary: Create a subscription
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSubscription'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    get:
      summary: List subscriptions
      parameters:
        - in: query
          name: user_id
          schema:
            type: string
        - in: query
          name: service_name
          schema:
            type: string
        - in: query
          name: limit
          schema:
            type: integer
            default: 50
        - in: query
          name: offset
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: List of subscriptions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Subscription'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /subscriptions/{id}:
    get:
      summary: Get subscription by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Subscription details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      summary: Update subscription by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateSubscription'
      responses:
        '200':
          description: Updated subscription
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Delete subscription by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No content (deleted)
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /subscriptions/aggregate:
    get:
      summary: Get total subscription cost for period
      parameters:
        - in: query
          name: from
          required: true
          schema:
            type: string
            example: '07-2025'
        - in: query
          name: to
          required: true
          schema:
            type: string
            example: '09-2025'
        - in: query
          name: user_id
          schema:
            type: string
        - in: query
          name: service_name
          schema:
            type: string
      responses:
        '200':
          description: Total cost
          content:
            application/json:
              schema:
                type: object
                properties:
                  from:
                    type: string
                  to:
                    type: string
                  total:
                    type: integer
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    CreateSubscription:
      type: object
      required:
        - service_name
        - price
        - user_id
        - start_date
      properties:
        service_name:
          type: string
        price:
          type: integer
        user_id:
          type: string
        start_date:
          type: string
          example: '07-2025'
        end_date:
          type: string
          nullable: true
          example: '12-2025'

    UpdateSubscription:
      type: object
      required:
        - service_name
        - price
        - user_id
        - start_date
      properties:
        service_name:
          type: string
        price:
          type: integer
        user_id:
          type: string
        start_date:
          type: string
          example: '07-2025'
        end_date:
          type: string
          nullable: true
          example: '12-2025'

    Subscription:
      type: object
      properties:
        id:
          type: string
        service_name:
          type: string
        price:
          type: integer
        user_id:
          type: string
        start_date:
          type: string
          example: '07-2025'
        end_date:
          type: string
          nullable: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    Error:
      type: object
      properties:
        code:
          type: integer
          description: Код ошибки
        message:
          type: string
          description: Описание ошибки
      required:
        - code
        - message
      example:
        code: 400
        message: 'Invalid request parameters'
